title: Wei Kiat Tan
logo: file:///C:/Users/weiki/OneDrive/Pictures/ry0a2wkn4sk71.jpg
description: 
minima:
  social_links:
    - {platform: github,  user_url: "https://github.com/wei-kiat-tan" }
    - {platform: linkedin, user_url: "https://www.linkedin.com/in/wei-kiat-tan/" }
show_downloads: 
google_analytics: UA-NNNNNNNN-N
theme: jekyll-theme-minimal



